# Generated by Django 4.2.5 on 2024-01-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(max_length=16)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
